### ISSUE TITLE
UNMET PEER DEPENDENCY when using with Angular v4

### ISSUE THREAD

**Issue by Pittan** [Tsmith18256/ng2-inline-href#1]
Hello 😀 
This code is awesome! You saved my life 😆 👍 

Except one thing,
When installing this package, npm is telling me warning.
Anyway, this package works fine with Angular v4.
Do you have any plans to update package.json to make this warning clear?

```
pc:awesome-project pittan$ npm install --save ng2-inline-href
awesome-project@0.0.0 /Users/pittan/Dev/awesome-project
├── UNMET PEER DEPENDENCY @angular/core@4.0.1
└── ng2-inline-href@1.0.0 

npm WARN ng2-inline-href@1.0.0 requires a peer of @angular/core@2.x.x but none was installed.
```

**Comment by Tsmith18256** [comment]
Hey @Pittan! Thanks for letting me know about. this, I have been pretty busy lately, but I am updating one of projects to Angular 4 soon and should be able to get the update rolled out to this package this week.

**Comment by Tsmith18256** [comment]
@Pittan I have updated the peer dependency to Angular 4. Note that the package has been moved from _ng2-inline-href_ to [ng-inline-href](https://www.npmjs.com/package/ng-inline-href).

Cheers!
