### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by chmanik** [Tsmith18256/ng2-inline-href#13]
Hi,
 I am getting below errors while adding BrowserAnimationsModule in my project.
Please help here.

Uncaught Error: Unexpected module 'BrowserAnimationsModule' declared by the module 'AppModule'. Please add a @Pipe/@Directive/@Component annotation.

**Comment by Tsmith18256** [comment]
Hey, did you get a stack trace or anything indicating some correlation between this error message and this library? I'm having a problem seeing how that error is related.

**Comment by Tsmith18256** [comment]
Closing as stale. If you are able to find a relationship between that error and this library, just let me know
