### ISSUE TITLE
Not working in modal

### ISSUE THREAD

**Issue by electerious** [Tsmith18256/ng2-inline-href#14]
I'm using the [`ng-bootstrap`](https://ng-bootstrap.github.io/#/components/modal/examples) modal in combination with `ng-inline-href`. `ng-inline-href` works fine on the site, but not when you use it inside a modal. The `inlineHref` attribute stays untouched.

I guess that the dynamically added modal somehow doesn't trigger `ng-inline-href` as there's no error or anything. 

The `InlineHrefModule` has been imported in `app.module.ts`. `app.module.ts` also imports the modal.

- Angular v5.2.9
- ng-bootstrap v2.0.0
- ng-inline-href v2.1.2

**Comment by Tsmith18256** [comment]
Hey, I'll see if I can figure this out over the weekend. Are you able to provide an example project so I can duplicate the issue easily?

**Comment by electerious** [comment]
No public project, sorry, but I've found the issue.

All my modals have been declared (`declarations`) in a dedicated module called `modals.module.ts` which then has been imported into `app.module.ts` togther with `InlineHrefModule`. Moving everything from `modal.module.ts` into `app.module.ts` fixes the issue.

Thanks for the module!
