### ISSUE TITLE
UNMET PEER DEPENDENCY when using with Angular v4.0.2

### ISSUE THREAD

**Issue by mlc-mlapis** [Tsmith18256/ng2-inline-href#2]
Hi,

there is a problem to install `npm install ng-inline-href` with actual version of Angular 4.0.2:

+-- UNMET PEER DEPENDENCY @angular/core@4.0.2 invalid
+-- ng-inline-href@2.0.1
`-- UNMET PEER DEPENDENCY tslint@5.1.0

As you can see there is the same problem with tslint@5.1.0

There are also some inaccuracies related to `ng2-inline-href` -> ` ng-inline-href`.

**Comment by Tsmith18256** [comment]
Hey @mlc-mlapis, could you please provide some more information into your issue. The only peer dependency for the module is `@angular/core` and the required version is set to `4.x.x`, which should match 4.0.2 with no problem.

As far as the tslint, this is not a requirement of _ng-inline-href_. 

Could you also please explain the inaccuracies you are referring to with `ng2-inline-href` -> `ng-inline-href`.

**Comment by mlc-mlapis** [comment]
Hello, I apologize for the previous incorrect info, the situation was somehow related to the inconsistent state when upgrading to Angular 4.0.3.

As for inaccuracies I had in mind `Setup` section in README.md where `ng2-inline-href` is probably still used instead of `ng-inline-href`. The same it is in https://www.npmjs.com/package/ng-inline-href

**Comment by Tsmith18256** [comment]
Ah, thanks for the update. I will make the changes required to the readme and, just to be sure, you got the code solved and I can close this once I have done the readme changes, right?
