### ISSUE TITLE
ts file missing after npm install

### ISSUE THREAD

**Issue by georgdonner** [Tsmith18256/ng2-inline-href#3]
Hi there,
I've got no problems with the dependencies and have ^4.0.0 for the angular core in my project. However, when I install the package (ng-inline-href), the module can't be found when importing in the module and I would assume it's because there's no ts file in the folder (only npmignore, package&tsconfig.json, readme and license). Can you maybe help me here? :)
Cheers, Georg

**Comment by Tsmith18256** [comment]
Hey @LinkinGeorge, can you reinstall from NPM and try it again now? I pushed to NPM from a different machine than I was testing the module from and I forgot to build the TypeScript on the machine I used to push the last version. 

The newest version (2.0.4) has the _inline-href.js_ and _inline-href.d.ts_ files, which are what you need.

**Comment by georgdonner** [comment]
Thanks, now it works perfectly! :)
