### ISSUE TITLE
Issue with Angular-CLI

### ISSUE THREAD

**Issue by bbonet** [Tsmith18256/ng2-inline-href#4]
Hi Tyler. I'm using ng-inline-href with angular-cli and I'm getting the following error in my javascript console when running my app.

<img width="639" alt="screen shot 2017-05-10 at 2 45 56 pm" src="https://cloud.githubusercontent.com/assets/178903/25920630/d5a09104-358f-11e7-904b-b2a8cb67b6b5.png">

It links to the following in my build.

<img width="701" alt="screen shot 2017-05-10 at 2 50 05 pm" src="https://cloud.githubusercontent.com/assets/178903/25920691/06329bfa-3590-11e7-8956-4053f2925087.png">

I'm guessing it's due to differences in build systems? I'm no wiz at javascript build systems. Angular-CLI just works and user webpack behind the scenes.

Let me know if you can help or if you want me to create an example repo.

Regards,
Brent

**Comment by Tsmith18256** [comment]
Hmmm, I haven't used this with the Angular CLI yet, most of my projects predate the CLI. I'll spin up a new project with it and see if I get the error as well; if not, I will let you know and require a sample project.

Thanks,
Tyler

**Comment by Tsmith18256** [comment]
Hey again @bbonet,

I have spun up a clean project with the Angular CLI using ng-inline-href directly from NPM and it is working fine on my machine. I definitely seethe like you're referring to with the `require()` statement, but it isn't causing any errors for me and the directive is doing what it should.

Could you do a couple things for me:
1. Try it with a new project and see what happens:
    1. Run `ng new <project-name>`
    2. Run `npm install -S ng-inline-href`
    3. Import `InlineHrefDirective` to your app component and add it to `declarations` and `exports`
    4. Add a simple usage of the directive to your HTML file (you can just point to a non-existent SVG file or something, we can still see if it worked by inspecting the DOM)
    5. Run `ng serve` and see if it works
2. If you can provide an demo repo that has the issue you described, just upload it to Github and send me a link so I can take a look at it and see if I can figure out the exact reason why you're having this problem.

Thanks,
Tyler

**Comment by bbonet** [comment]
Hi Tyler - I'm crunching for the end of a sprint this week. I spoke with the html developer who is using the component and he said that despite the error, everything is working fine. Still it would be nice to resolve the error. I'll try to do some tests for you over the weekend. 

Regards - Brent

**Comment by bbonet** [comment]
I thought that maybe it was because we're using ng4. -ng4 flag in ng new. The error didn't show up so I'll keep digging. Thanks for your help.  Regards - Brent
