### ISSUE TITLE
Exports is not defined on ng4

### ISSUE THREAD

**Issue by bbonet** [Tsmith18256/ng2-inline-href#5]
Hi Tyler - The user story came back to me so I started some tests.

If I generate the project with 
`ng new inline-href-ng4-test -ng4`

and run 
`npm install --save ng-inline-href`

and add the module to the .angular-cli.json file
`"scripts": ["../node_modules/ng-inline-href/inline-href.js"],`

then run
`npm run start`

The error shows up in the javascript console of chrome.
<img width="686" alt="screen shot 2017-05-24 at 11 27 01 am" src="https://cloud.githubusercontent.com/assets/178903/26416672/fa43bea2-4073-11e7-9de2-5d643ff15333.png">

If I do the same as above but leave the ng4 flag out
`ng new inline-href-ng2-test`

I do not get the error.

Let me know if you can recreate.

Thanks - Brent

**Comment by Tsmith18256** [comment]
Hey, which version of the CLI are you using? The `ng4` flag was ripped out for version 1.0 of the CLI to become the default behaviour. The test project I made was done with the newest CLI, with no flags, and was therefore also an Angular 4 project.

**Comment by bbonet** [comment]
1.0.4. If that the case I'll do another test.

**Comment by bbonet** [comment]
Like an idiot I was importing it with the scripts in .angular-cli.json.
