### ISSUE TITLE
Directive generating undefined in production

### ISSUE THREAD

**Issue by Tsmith18256** [Tsmith18256/ng2-inline-href#8]
Originally reported by @LinkinGeorge in #6. 

When using ng-inline-href, it is working correctly; however, when running it with the `--prod` flag, it is generating `href="http://localhost:4200/undefined"`.

**Comment by nbijl-worthit** [comment]
any idea when we can expect a fix?

**Comment by Tsmith18256** [comment]
I'm going to be looking at this today. Hopefully it's simple enough to get it fixed today; otherwise, it will depend how long it takes me to track down the issue.

**Comment by Tsmith18256** [comment]
Ugh, basically the same issue, but this time it was with the `@Input()` decorator and wasn't throwing an error. 

Thanks for reporting this stuff @LinkinGeorge and @nbijl-worthit, the directive should be ready for production with Angular 4 now. Installing 2.0.6 of _ng-inline-href_ from NPM renders the SVG properly in the demo project @LinkinGeorge gave me.
